import { createHash, createHmac } from 'node:crypto';

// Where uploaded files live. The API stores and serves them; browsers never
// hold storage credentials.
export interface FileStorage {
  readonly name: string;
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

// Tests and local development. Files are lost on restart; configuration
// refuses it in production.
export class MemoryStorage implements FileStorage {
  readonly name = 'memory';
  readonly objects = new Map<string, { body: Buffer; contentType: string }>();
  put(key: string, body: Buffer, contentType: string) {
    this.objects.set(key, { body: Buffer.from(body), contentType });
    return Promise.resolve();
  }
  get(key: string) {
    return Promise.resolve(this.objects.get(key)?.body ?? null);
  }
  delete(key: string) {
    this.objects.delete(key);
    return Promise.resolve();
  }
}

const sha256 = (data: string | Buffer) =>
  createHash('sha256').update(data).digest('hex');
const hmac = (key: string | Buffer, data: string) =>
  createHmac('sha256', key).update(data).digest();

// AWS Signature Version 4 for one S3 request. Header names must be lower
// case; every header given is signed.
export function signS3Request(input: {
  method: string;
  host: string;
  path: string;
  region: string;
  accessKeyId: string;
  secretAccessKey: string;
  amzDate: string;
  payloadHash: string;
  headers?: Record<string, string>;
}) {
  const headers: Record<string, string> = {
    ...input.headers,
    host: input.host,
    'x-amz-content-sha256': input.payloadHash,
    'x-amz-date': input.amzDate,
  };
  const names = Object.keys(headers).sort();
  const canonicalHeaders = names
    .map((n) => `${n}:${headers[n]!.trim()}\n`)
    .join('');
  const signedHeaders = names.join(';');
  const canonical = [
    input.method,
    input.path,
    '',
    canonicalHeaders,
    signedHeaders,
    input.payloadHash,
  ].join('\n');
  const day = input.amzDate.slice(0, 8);
  const scope = `${day}/${input.region}/s3/aws4_request`;
  const toSign = [
    'AWS4-HMAC-SHA256',
    input.amzDate,
    scope,
    sha256(canonical),
  ].join('\n');
  const key = hmac(
    hmac(hmac(hmac(`AWS4${input.secretAccessKey}`, day), input.region), 's3'),
    'aws4_request',
  );
  const signature = createHmac('sha256', key).update(toSign).digest('hex');
  return {
    ...headers,
    authorization: `AWS4-HMAC-SHA256 Credential=${input.accessKeyId}/${scope}, SignedHeaders=${signedHeaders}, Signature=${signature}`,
  };
}

// Cloudflare R2 through its S3-compatible API (path-style, region "auto").
export class R2Storage implements FileStorage {
  readonly name = 'r2';
  private readonly host: string;
  constructor(
    private readonly config: {
      accountId: string;
      accessKeyId: string;
      secretAccessKey: string;
      bucket: string;
    },
    private readonly fetcher: typeof fetch = fetch,
  ) {
    this.host = `${config.accountId}.r2.cloudflarestorage.com`;
  }

  private async request(
    method: 'PUT' | 'GET' | 'DELETE',
    key: string,
    body?: Buffer,
    contentType?: string,
  ) {
    // Keys are generated by Acticlaim (purpose/uuid), so they need no escaping
    // beyond what encodeURIComponent does per segment.
    const path = `/${this.config.bucket}/${key.split('/').map(encodeURIComponent).join('/')}`;
    const amzDate = new Date().toISOString().replace(/[-:]|\.\d{3}/g, '');
    const headers = signS3Request({
      method,
      host: this.host,
      path,
      region: 'auto',
      accessKeyId: this.config.accessKeyId,
      secretAccessKey: this.config.secretAccessKey,
      amzDate,
      payloadHash: sha256(body ?? ''),
      headers: contentType ? { 'content-type': contentType } : {},
    });
    const response = await this.fetcher(`https://${this.host}${path}`, {
      method,
      headers,
      ...(body ? { body: new Uint8Array(body) } : {}),
      signal: AbortSignal.timeout(20000),
    });
    return response;
  }

  async put(key: string, body: Buffer, contentType: string) {
    const response = await this.request('PUT', key, body, contentType);
    if (!response.ok) throw new Error(`Storage put failed: ${response.status}`);
  }
  async get(key: string) {
    const response = await this.request('GET', key);
    if (response.status === 404) return null;
    if (!response.ok) throw new Error(`Storage get failed: ${response.status}`);
    return Buffer.from(await response.arrayBuffer());
  }
  async delete(key: string) {
    const response = await this.request('DELETE', key);
    if (!response.ok && response.status !== 404)
      throw new Error(`Storage delete failed: ${response.status}`);
  }
}
